server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/master-data-service_db?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: masterdata_stc
    password: Mul7417064@
    driver-class-name: com.mysql.cj.jdbc.Driver

    ## Spring JPA
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}